[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9.23" # TODO: fix getrandom error on modern versions
spin = "0.9.8"
volatile = "0.2.6"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]
